<?php

namespace Database\Seeders;

use App\Models\Oferta;
use App\Models\Producto;
use App\Models\Talla;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $oferta1 = Oferta::create([
            'nombre' => 'Descuento Verano',
            'descuento' => 20, // 20%
            'inicio' => now(),
            'fin' => now()->addDays(30),
        ]);

        $oferta2 = Oferta::create([
            'nombre' => 'Descuento Invierno',
            'descuento' => 10, // 10%
            'inicio' => now(),
            'fin' => now()->addDays(10),
        ]);

        $productosRopa = [
            [
                'nombre' => 'Americana Azul Marino Slim Fit',
                'descripcion' => 'Americana azul marino de ajuste entallado con dos botones y bolsillos delanteros.',
                'precio' => 79.99,
                'principalImg' => 'Americana_Azul_Marino_Slim_Fit.webp',
                'img1' => 'americana_azul_marino1.webp',
                'categoria_id' => 1, // ID de la categoría "Americanas" para hombres
            ],
            [
                'nombre' => 'Americana Gris Elegante',
                'descripcion' => 'Americana gris de corte clásico con un solo botón y solapa de muesca.',
                'precio' => 89.99,
                'principalImg' => 'Americana_Gris_Elegante.webp',
                'img1' => 'americana_gris1.webp',
                'categoria_id' => 1, // ID de la categoría "Americanas" para hombres
            ],
            [
                'nombre' => 'Traje Azul Oscuro con Rayas',
                'descripcion' => 'Traje de dos piezas en azul oscuro con rayas finas. Incluye americana y pantalón a juego.',
                'precio' => 149.99,
                'principalImg' => 'Traje_Azul_Oscuro_con_Rayas.webp',
                'img1' => 'traje_azul_rayas1.webp',
                'categoria_id' => 1, // ID de la categoría "Americanas" para hombres
            ],
            [
                'nombre' => 'Americana Casual de Lino',
                'descripcion' => 'Americana casual en tejido de lino natural con cierre de botones y bolsillos laterales.',
                'precio' => 69.99,
                'principalImg' => 'Americana_Casual_de_Lino.webp',
                'img1' => 'americana_lino1.webp',
                'categoria_id' => 1, // ID de la categoría "Americanas" para hombres
            ],[
                'nombre' => 'Camisa de Cuadros',
                'descripcion' => 'Camisa de manga larga con diseño de cuadros en tonos azules y blancos.',
                'precio' => 39.99,
                'principalImg' => 'camisa_cuadros.webp',
                'img1' => 'camisa_cuadros1.webp',
                'categoria_id' => 2, // ID de la categoría "Camisas" para hombres
            ],
            [
                'nombre' => 'Camisa Vaquera',
                'descripcion' => 'Camisa vaquera de estilo clásico con cierre de botones y bolsillos en el pecho.',
                'precio' => 49.99,
                'principalImg' => 'camisa_vaquera.webp',
                'img1' => 'camisa_vaquera1.webp',
                'categoria_id' => 2, // ID de la categoría "Camisas" para hombres
            ],
            [
                'nombre' => 'Camisa de Vestir Blanca',
                'descripcion' => 'Camisa de vestir blanca de algodón con corte ajustado y cuello clásico.',
                'precio' => 59.99,
                'principalImg' => 'camisa_vestir_blanca.webp',
                'img1' => 'camisa_vestir_blanca1.webp',
                'categoria_id' => 2, // ID de la categoría "Camisas" para hombres
            ],
            [
                'nombre' => 'Camisa de Lino',
                'descripcion' => 'Camisa de lino transpirable con botones y bolsillo en el pecho.',
                'precio' => 44.99,
                'principalImg' => 'camisa_lino.webp',
                'img1' => 'camisa_lino1.webp',
                'categoria_id' => 2, // ID de la categoría "Camisas" para hombres
            ],[
                'nombre' => 'Polo de Algodón Piqué',
                'descripcion' => 'Polo de manga corta en algodón piqué con cuello de polo y logo bordado en el pecho.',
                'precio' => 29.99,
                'principalImg' => 'polo_pique.webp',
                'img1' => 'polo_pique1.webp',
                'categoria_id' => 3, // ID de la categoría "Polos" para hombres
            ],
            [
                'nombre' => 'Polo Slim Fit',
                'descripcion' => 'Polo ajustado de manga corta con cuello clásico y detalles de rayas en el cuello y mangas.',
                'precio' => 34.99,
                'principalImg' => 'polo_slim_fit.webp',
                'img1' => 'polo_slim_fit1.webp',
                'categoria_id' => 3, // ID de la categoría "Polos" para hombres
            ],
            [
                'nombre' => 'Polo de Rayas',
                'descripcion' => 'Polo de algodón de manga corta con diseño de rayas en contraste y detalle de logo en el pecho.',
                'precio' => 31.99,
                'principalImg' => 'polo_rayas.webp',
                'img1' => 'polo_rayas1.webp',
                'categoria_id' => 3, // ID de la categoría "Polos" para hombres
            ],
            [
                'nombre' => 'Polo de Golf',
                'descripcion' => 'Polo de golf de alto rendimiento con tecnología de secado rápido y protección solar UPF 50+.',
                'precio' => 49.99,
                'principalImg' => 'polo_golf.webp',
                'img1' => 'polo_golf1.webp',
                'categoria_id' => 3, // ID de la categoría "Polos" para hombres
            ],[
                'nombre' => 'Pantalón Chino Slim Fit',
                'descripcion' => 'Pantalón chino de corte ajustado con bolsillos laterales y traseros. Ideal para un look casual.',
                'precio' => 49.99,
                'principalImg' => 'pantalon_chino.webp',
                'img1' => 'pantalon_chino1.webp',
                'categoria_id' => 4, // ID de la categoría "Pantalones" para hombres
            ],
            [
                'nombre' => 'Jeans Clásicos Rectos',
                'descripcion' => 'Jeans clásicos de corte recto con lavado vintage y detalles de costuras contrastantes.',
                'precio' => 59.99,
                'principalImg' => 'jeans_clasicos.webp',
                'img1' => 'jeans_clasicos1.webp',
                'categoria_id' => 4, // ID de la categoría "Pantalones" para hombres
            ],
            [
                'nombre' => 'Pantalón Cargo',
                'descripcion' => 'Pantalón cargo de algodón resistente con múltiples bolsillos y cintura ajustable.',
                'precio' => 54.99,
                'principalImg' => 'pantalon_cargo.webp',
                'img1' => 'pantalon_cargo1.webp',
                'categoria_id' => 4, // ID de la categoría "Pantalones" para hombres
            ],
            [
                'nombre' => 'Pantalón Jogger',
                'descripcion' => 'Pantalón jogger de tejido suave y elástico con cintura elástica y puños ajustados.',
                'precio' => 39.99,
                'principalImg' => 'pantalon_jogger.webp',
                'img1' => 'pantalon_jogger1.webp',
                'categoria_id' => 4, // ID de la categoría "Pantalones" para hombres
            ],[
                'nombre' => 'Sudadera con Capucha Gris',
                'descripcion' => 'Sudadera gris con capucha y bolsillo canguro en la parte delantera.',
                'precio' => 39.99,
                'principalImg' => 'sudadera_gris.webp',
                'img1' => 'sudadera_gris1.webp',
                'categoria_id' => 5, // ID de la categoría "Sudaderas" para hombres
            ],
            [
                'nombre' => 'Sudadera Estampada Foto',
                'descripcion' => 'Sudadera negra con parche de fotografía en el pecho y mangas largas.',
                'precio' => 44.99,
                'principalImg' => 'sudadera_negra.webp',
                'img1' => 'sudadera_negra1.webp',
                'categoria_id' => 5, // ID de la categoría "Sudaderas" para hombres
            ],
            [
                'nombre' => 'Sudadera Deportiva Azul',
                'descripcion' => 'Sudadera azul de estilo deportivo con cierre de cremallera y detalles reflectantes.',
                'precio' => 49.99,
                'principalImg' => 'sudadera_azul.webp',
                'img1' => 'sudadera_azul1.webp',
                'categoria_id' => 5, // ID de la categoría "Sudaderas" para hombres
            ],
            [
                'nombre' => 'Sudadera Oversize Verde',
                'descripcion' => 'Sudadera verde oversize con cuello redondo y tejido suave de algodón.',
                'precio' => 54.99,
                'principalImg' => 'sudadera_verde.webp',
                'img1' => 'sudadera_verde1.webp',
                'categoria_id' => 5, // ID de la categoría "Sudaderas" para hombres
            ],
            [
                'nombre' => 'Chaqueta de Cuero Negra',
                'descripcion' => 'Chaqueta de cuero negra con cierre de cremallera y bolsillos laterales.',
                'precio' => 149.99,
                'principalImg' => 'chaqueta_cuero_negra.webp',
                'img1' => 'chaqueta_cuero_negra1.webp',
                'categoria_id' => 6, // ID de la categoría "Chaquetas" para hombres
            ],
            [
                'nombre' => 'Chaqueta Bomber',
                'descripcion' => 'Chaqueta bomber en azul marino con puños y cuello acanalados y cierre de cremallera.',
                'precio' => 99.99,
                'principalImg' => 'chaqueta_bomber.webp',
                'img1' => 'chaqueta_bomber_azul1',
                'categoria_id' => 6, // ID de la categoría "Chaquetas" para hombres
            ],
            [
                'nombre' => 'Chaqueta Vaquera',
                'descripcion' => 'Chaqueta vaquera en tono desgastado con cierre de botones y bolsillos en el pecho.',
                'precio' => 79.99,
                'principalImg' => 'chaqueta_vaquera.webp',
                'img1' => 'chaqueta_vaquera1.webp',
                'categoria_id' => 6, // ID de la categoría "Chaquetas" para hombres
            ],
            [
                'nombre' => 'Chaqueta Acolchada',
                'descripcion' => 'Chaqueta acolchada en color gris con capucha desmontable y cierre de cremallera.',
                'precio' => 119.99,
                'principalImg' => 'chaqueta_acolchada.webp',
                'img1' => 'chaqueta_acolchada_atras.webp',
                'categoria_id' => 6, // ID de la categoría "Chaquetas" para hombres
            ],
            [
                'nombre' => 'Bañador Corto Azul',
                'descripcion' => 'Bañador corto azul con cintura elástica y bolsillos laterales.',
                'precio' => 29.99,
                'principalImg' => 'banador_azul.webp',
                'img1' => 'banador_azul1.webp',
                'categoria_id' => 7, // ID de la categoría "Bañadores" para hombres
            ],
            [
                'nombre' => 'Bañador Estampado Floral',
                'descripcion' => 'Bañador estampado floral con cordón ajustable en la cintura y bolsillo trasero con cierre de velcro.',
                'precio' => 34.99,
                'principalImg' => 'banador_floral.webp',
                'img1' => 'banador_floral1.webp',
                'categoria_id' => 7, // ID de la categoría "Bañadores" para hombres
            ],
            [
                'nombre' => 'Bañador Surf Rojo',
                'descripcion' => 'Bañador para surf en color rojo con tecnología de secado rápido y bolsillo lateral con cierre de cremallera.',
                'precio' => 39.99,
                'principalImg' => 'banador_surf_rojo.webp',
                'img1' => 'banador_surf_rojo1.webp',
                'categoria_id' => 7, // ID de la categoría "Bañadores" para hombres
            ],
            [
                'nombre' => 'Bañador Deportivo Azul',
                'descripcion' => 'Bañador deportivo en azul con paneles laterales de malla y forro interior de malla.',
                'precio' => 44.99,
                'principalImg' => 'banador_deportivo_azul.webp',
                'img1' => 'banador_deportivo_azul1.webp',
                'categoria_id' => 7, // ID de la categoría "Bañadores" para hombres
            ],[
                'nombre' => 'Abrigo de Lana Camel',
                'descripcion' => 'Abrigo de lana en color camel con cierre de botones y bolsillos laterales.',
                'precio' => 99.99,
                'principalImg' => 'abrigo_lana_camel.webp',
                'img1' => 'abrigo_lana_camel1.webp',
                'categoria_id' => 8, // ID de la categoría "Abrigos" para mujeres
            ],[
                'nombre' => 'Abrigo corto gris',
                'descripcion' => 'Abrigo de corto en color gris con cierre de cremallera',
                'precio' => 119.99,
                'principalImg' => 'abrigo_mujer_gris.webp',
                'img1' => 'abrigo_mujer_gris1.webp',
                'categoria_id' => 8,
            ],
            [
                'nombre' => 'Abrigo de Cuero Negro',
                'descripcion' => 'Abrigo de cuero en color negro con cierre de cremallera y detalles acolchados en los hombros.',
                'precio' => 179.99,
                'principalImg' => 'abrigo_cuero_negro.webp',
                'img1' => 'abrigo_cuero_negro1.webp',
                'categoria_id' => 8,
            ],
            [
                'nombre' => 'Trenca de Lana con Capucha',
                'descripcion' => 'Trenca de lana con capucha desmontable y cierre de botones y cremallera.',
                'precio' => 149.99,
                'principalImg' => 'trenca_lana_capucha.webp',
                'img1' => 'trenca_lana_capucha1.webp',
                'categoria_id' => 8,
            ],[
                'nombre' => 'Pantalón Palazzo Negro',
                'descripcion' => 'Pantalón palazzo de tela ligera en color negro con cintura elástica.',
                'precio' => 59.99,
                'principalImg' => 'pantalon_palazzo_negro.webp',
                'img1' => 'pantalon_palazzo_negro1.webp',
                'categoria_id' => 9, // ID de la categoría "Pantalones" para mujeres
            ],
            [
                'nombre' => 'Leggings de Cuero',
                'descripcion' => 'Leggings ajustados de cuero sintético en color negro con detalle de cremalleras en los tobillos.',
                'precio' => 39.99,
                'principalImg' => 'leggings_cuero_negro.webp',
                'img1' => 'leggings_cuero_negro1.webp',
                'categoria_id' => 9,
            ],
            [
                'nombre' => 'Pantalón Jogger de Tela',
                'descripcion' => 'Pantalón jogger de tela suave en color gris con cintura elástica y puños ajustados.',
                'precio' => 49.99,
                'principalImg' => 'pantalon_jogger_tela.webp',
                'img1' => 'pantalon_jogger_tela1.webp',
                'categoria_id' => 9,
            ],
            [
                'nombre' => 'Pantalón Recto de Vestir',
                'descripcion' => 'Pantalón recto de vestir en color azul marino con bolsillos laterales y cierre de gancho y cremallera.',
                'precio' => 79.99,
                'principalImg' => 'pantalon_recto_vestir.webp',
                'img1' => 'pantalon_recto_vestir1.webp',
                'categoria_id' => 9,
            ],
            [
                'nombre' => 'Chaleco Acolchado Negro',
                'descripcion' => 'Chaleco acolchado en color negro con cierre de cremallera y bolsillos laterales con cremallera.',
                'precio' => 49.99,
                'principalImg' => 'chaleco_acolchado_negro.webp',
                'img1' => 'chaleco_acolchado_negro1.webp',
                'categoria_id' => 10, // ID de la categoría "Chalecos" para mujeres
            ],
            [
                'nombre' => 'Chaleco de Piel Sintética Marrón',
                'descripcion' => 'Chaleco de piel sintética en color marrón con forro de pelo sintético y cierre de gancho y ojo.',
                'precio' => 69.99,
                'principalImg' => 'chaleco_piel_sintetica_marron.webp',
                'img1' => 'chaleco_piel_sintetica_marron1.webp',
                'categoria_id' => 10,
            ],
            [
                'nombre' => 'Chaleco Tejido Gris',
                'descripcion' => 'Chaleco tejido en color gris con detalle de trenzado y cierre de botones en la parte delantera.',
                'precio' => 39.99,
                'principalImg' => 'chaleco_tejido_gris.webp',
                'img1' => 'chaleco_tejido_gris1.webp',
                'categoria_id' => 10,
            ],
            [
                'nombre' => 'Chaleco Lino blanco',
                'descripcion' => 'Chaleco lino en color blanco con cierre de botones',
                'precio' => 54.99,
                'principalImg' => 'chaleco_lino_blanco.webp',
                'img1' => 'chaleco_lino_blanco1.webp',
                'categoria_id' => 10,
            ],[
                'nombre' => 'Camisa blanca lino',
                'descripcion' => 'camisa de lino en color blanco',
                'precio' => 79.99,
                'principalImg' => 'Camisa_blanca_lino.webp',
                'img1' => 'Camisa_blanca_lino1.webp',
                'categoria_id' => 11, // ID de la categoría "Blusas y camisas" para mujeres
            ],
            [
                'nombre' => 'Camisa manga corta estampada',
                'descripcion' => 'Camisa de manga larga con estampado de cuadros en tonos rojos y blancos y cierre de botones.',
                'precio' => 49.99,
                'principalImg' => 'Camisa_manga_corta_estampada.webp',
                'img1' => 'Camisa_manga_corta_estampada1.webp',
                'categoria_id' => 11,
            ],
            [
                'nombre' => 'Blusa Floral',
                'descripcion' => 'Blusa de manga corta con estampado floral en tonos azules y detalle de lazada en el cuello.',
                'precio' => 59.99,
                'principalImg' => 'blusa_floral.webp',
                'img1' => 'blusa_floral1.webp',
                'categoria_id' => 11,
            ],
            [
                'nombre' => 'Camisa Vaquera Desgastada',
                'descripcion' => 'Camisa vaquera en tono desgastado con cierre de botones y bolsillos en el pecho.',
                'precio' => 64.99,
                'principalImg' => 'camisa_vaquera_desgastada.webp',
                'img1' => 'camisa_vaquera_desgastada1.webp',
                'categoria_id' => 11,
            ],[
                'nombre' => 'Top de Encaje Negro',
                'descripcion' => 'Top de encaje en color negro con tirantes finos y detalle de volantes en el escote.',
                'precio' => 39.99,
                'principalImg' => 'top_encaje_negro.webp',
                'img1' => 'top_encaje_negro1.webp',
                'categoria_id' => 12, // ID de la categoría "Tops" para mujeres
            ],
            [
                'nombre' => 'Top de Punto Beige',
                'descripcion' => 'Top de punto en color beige con cuello alto y manga larga.',
                'precio' => 29.99,
                'principalImg' => 'top_punto_beige.webp',
                'img1' => 'top_punto_beige1.webp',
                'categoria_id' => 12,
            ],
            [
                'nombre' => 'Top Crop de Terciopelo',
                'descripcion' => 'Top crop de terciopelo en color verde oscuro con escote en V y tirantes ajustables.',
                'precio' => 49.99,
                'principalImg' => 'top_crop_terciopelo.webp',
                'img1' => 'top_crop_terciopelo1.webp',
                'categoria_id' => 12,
            ],
            [
                'nombre' => 'Top de Tirantes',
                'descripcion' => 'Top de tirantes de color blanco y con cremallera.',
                'precio' => 34.99,
                'principalImg' => 'top_tirantes.webp',
                'img1' => 'top_tirantes1.webp',
                'categoria_id' => 12,
            ],[
                'nombre' => 'Bikini de Rayas Azules',
                'descripcion' => 'Conjunto de bikini de dos piezas con estampado de rayas en azul y blanco.',
                'precio' => 49.99,
                'principalImg' => 'bikini_rayas_azules.webp',
                'img1' => 'bikini_rayas_azules1.webp',
                'categoria_id' => 13, // ID de la categoría "Bikinis" para mujeres
            ],
            [
                'nombre' => 'Bikini Tropical',
                'descripcion' => 'Conjunto de bikini de dos piezas con estampado tropical y detalles de volantes.',
                'precio' => 54.99,
                'principalImg' => 'bañador_mujer.webp',
                'img1' => 'bañador_mujer1.webp',
                'categoria_id' => 13,
            ],
            [
                'nombre' => 'Bañador',
                'descripcion' => 'Bañador azul.',
                'precio' => 39.99,
                'principalImg' => 'bañador_mujer.webp',
                'img1' => 'bañador_mujer1.webp',
                'categoria_id' => 13,
            ],
            [
                'nombre' => 'Bikini metalizado',
                'descripcion' => 'Conjunto de bikini de dos piezas con diseño metalizado.',
                'precio' => 44.99,
                'principalImg' => 'bikini_metalizado.webp',
                'img1' => 'bikini_metalizado1.webp',
                'categoria_id' => 13,
            ],[
                'nombre' => 'Falda Midi metalizada',
                'descripcion' => 'Falda midi plisada en color metalizado con cintura elástica.',
                'precio' => 59.99,
                'principalImg' => 'falda_midi_metalizada.webp',
                'img1' => 'falda_midi_metalizada1.webp',
                'categoria_id' => 14, // ID de la categoría "Faldas" para mujeres
            ],
            [
                'nombre' => 'Falda Lápiz Negra',
                'descripcion' => 'Falda lápiz de tubo en color negro con detalle de abertura en la parte trasera.',
                'precio' => 44.99,
                'principalImg' => 'falda_lapiz_negra.webp',
                'img1' => 'falda_lapiz_negra1.webp',
                'categoria_id' => 14,
            ],
            [
                'nombre' => 'Falda Vaquera Desgastada',
                'descripcion' => 'Falda vaquera en tono desgastado con botones en la parte delantera y bolsillos laterales.',
                'precio' => 49.99,
                'principalImg' => 'falda_vaquera_desgastada.webp',
                'img1' => 'falda_vaquera_desgastada1.webp',
                'categoria_id' => 14,
            ],
            [
                'nombre' => 'Falda Plisada Metalizada',
                'descripcion' => 'Falda plisada en color plateado metalizado con cintura elástica y forro interior.',
                'precio' => 64.99,
                'principalImg' => 'falda_midi_plisada.webp',
                'img1' => 'falda_midi_plisada1.webp',
                'categoria_id' => 14,
            ],
            [
                'nombre' => 'Vestido Midi Floral',
                'descripcion' => 'Vestido midi con estampado floral en tonos pastel y cintura ajustada.',
                'precio' => 69.99,
                'principalImg' => 'vestido_midi_floral.webp',
                'img1' => 'vestido_midi_floral1.webp',
                'categoria_id' => 15, // ID de la categoría "Vestidos" para mujeres
            ],
            [
                'nombre' => 'Vestido Maxi Boho',
                'descripcion' => 'Vestido maxi estilo bohemio con estampado étnico y detalle de volantes en el bajo.',
                'precio' => 79.99,
                'principalImg' => 'vestido_maxi_boho.webp',
                'img1' => 'vestido_maxi_boho1.webp',
                'categoria_id' => 15,
            ],
            [
                'nombre' => 'Vestido estampado lazo',
                'descripcion' => 'Vestido estampado lazo en color amarillo',
                'precio' => 59.99,
                'principalImg' => 'vestido_estampado.webp',
                'img1' => 'vestido_estampado1.webp',
                'categoria_id' => 15,
            ],
            [
                'nombre' => 'Vestido Estampado Retro',
                'descripcion' => 'Vestido corto con estampado retro en colores vivos y cuello redondo.',
                'precio' => 54.99,
                'principalImg' => 'vestido_estampado_retro.webp',
                'img1' => 'vestido_estampado_retro1.webp',
                'categoria_id' => 15,
            ],
            [
                'nombre' => 'Vestido Floral Rosa',
                'descripcion' => 'Vestido rosa con estampado floral y lazo en la cintura.',
                'precio' => 29.99,
                'principalImg' => 'vestido_floral_rosa.webp',
                'img1' => 'vestido_floral_rosa1.webp',
                'categoria_id' => 16,
            ],
            [
                'nombre' => 'Vestido estampado tie dye',
                'descripcion' => 'Vestido estampado tie dye de color azul y blanco.',
                'precio' => 34.99,
                'principalImg' => 'vestido_estampado_tie_dye.webp',
                'img1' => 'vestido_estampado_tie_dye1.webp',
                'categoria_id' => 16,
            ],
            [
                'nombre' => 'Vestido plumeti lazo',
                'descripcion' => 'Vestido plumeti lazo de color blanco. Con cierre de lazo.',
                'precio' => 27.99,
                'principalImg' => 'vestido_plumeti_lazo.webp',
                'img1' => 'vestido_plumeti_lazo1.webp',
                'categoria_id' => 16,
            ],
            [
                'nombre' => 'Vestido estampado paisley',
                'descripcion' => '100% algodón. Estampado paisley. Diseño recto. Diseño corto. Detalles fruncidos. Tirantes fruncidos. Cuello cuadrado. Sin mangas.',
                'precio' => 24.99,
                'principalImg' => 'vestido_estampado_paisley.webp',
                'img1' => 'vestido_estampado_paisley1.webp',
                'categoria_id' => 16,
            ],[
                'nombre' => 'Blusa plumeti bordado',
                'descripcion' => '100% algodón. Tejido plumeti. Detalle bordado. Diseño recto. Manga corta. Cierre de botones.',
                'precio' => 19.99,
                'principalImg' => 'blusa_plumeti_bordado.webp',
                'img1' => 'blusa_plumeti_bordado1.webp',
                'categoria_id' => 17, // ID de la categoría "Camisas y blusas" para niñas
            ],
            [
                'nombre' => 'Blusa lino botones',
                'descripcion' => 'Tejido mezcla de algodón y lino. Diseño recto. Cierre de botones. Cuello babydoll. Sin mangas.',
                'precio' => 22.99,
                'principalImg' => 'blusa_lino_botones.webp',
                'img1' => 'blusa_lino_botones1.webp',
                'categoria_id' => 17,
            ],
            [
                'nombre' => 'Blusa estampada fruncido',
                'descripcion' => 'Conjunto. Total look. 100% algodón. Diseño recto. Estampado. Detalle fruncido. Cuello barco. Manga corta. Sin cierre.',
                'precio' => 18.99,
                'principalImg' => 'blusa_estampada_fruncido.webp',
                'img1' => 'blusa_estampada_fruncido1.webp',
                'categoria_id' => 17,
            ],
            [
                'nombre' => 'Blusa volantes lino',
                'descripcion' => 'Conjunto. Total look. Tejido mezcla de algodón y lino. Estampada. Diseño recto. Diseño corto. Manga corta con volante. Cuello redondo. Cierre de botón.',
                'precio' => 25.99,
                'principalImg' => 'blusa_volantes_lino.webp',
                'img1' => 'blusa_volantes_lino1.webp',
                'categoria_id' => 17,
            ],[
                'nombre' => 'Abrigo doble botonadura',
                'descripcion' => 'Tejido de lana. Diseño doble botonadura. Diseño corto. Diseño recto. Solapas. Dos bolsillos delanteros. Manga larga. Cierre delantero. Cierre de botones.',
                'precio' => 49.99,
                'principalImg' => 'abrigo_doble_botonadura.webp',
                'img1' => 'abrigo_doble_botonadura1.webp',
                'categoria_id' => 18, // ID de la categoría "Abrigos" para niñas
            ],
            [
                'nombre' => 'Chaqueta tweed bolsillos',
                'descripcion' => 'Tejido de algodón. Tejido tweed. Diseño corto. Diseño recto. Cuello redondo. Manga larga. Dos bolsillos delanteros. Cierre delantero. Cierre de dos botones.',
                'precio' => 54.99,
                'principalImg' => 'chaqueta_tweed_bolsillos.webp',
                'img1' => 'chaqueta_tweed_bolsillos1.webp',
                'categoria_id' => 18,
            ],
            [
                'nombre' => 'Chaqueta vaquera',
                'descripcion' => 'Tejido de algodón estilo tejano vaquero. Diseño recto. Diseño volantes. Cuello camisero. Manga larga. Cierre delantero. Cierre de botones.',
                'precio' => 59.99,
                'principalImg' => 'chaqueta_vaquera_niña.webp',
                'img1' => 'chaqueta_vaquera_niña1.webp',
                'categoria_id' => 18,
            ],
            [
                'nombre' => 'Abrigo lana botones',
                'descripcion' => 'Colección fiesta y ceremonia. Colección Navidad. Tejido de lana. Diseño recto. Diseño largo. Dos bolsillos de solapa. Manga larga. Cierre delantero. Cierre de botones. Etiqueta interior para datos personales .',
                'precio' => 44.99,
                'principalImg' => 'abrigo_lana_botones.webp',
                'img1' => 'abrigo_lana_botones1.webp',
                'categoria_id' => 18,
            ],[
                'nombre' => 'Pantalón recto estampado',
                'descripcion' => 'Conjunto. Total look. 100% algodón. Diseño largo. Estampado. Diseño recto. Sin cierre.',
                'precio' => 29.99,
                'principalImg' => 'pantalones_niña.webp',
                'img1' => 'pantalones_niña1 .webp',
                'categoria_id' => 19, // ID de la categoría "Pantalones" para niñas
            ],
            [
                'nombre' => 'Pantalón pinzas cinturón',
                'descripcion' => 'Detalle de pinzas. Cintura elástica. Cinturón decorativo. Trabillas. Goma elástica. Cinturón ajustable.',
                'precio' => 27.99,
                'principalImg' => 'pantalones_niña2.webp',
                'img1' => 'pantalones_niña3.webp',
                'categoria_id' => 19,
            ],
            [
                'nombre' => 'Pantalón lino botones',
                'descripcion' => 'Tejido de lino. Diseño recto. Diseño largo. Botones decorativos. Dos bolsillos laterales. Goma elástica. Cintura elástica. Sin cierre.',
                'precio' => 19.99,
                'principalImg' => 'pantalones_niña4.webp',
                'img1' => 'pantalones_niña5.webp',
                'categoria_id' => 19,
            ],
            [
                'nombre' => 'Pantalón lyocell cintura elástica',
                'descripcion' => 'Total look. Tejido de lyocell. Efecto denim. Diseño culotte. Diseño palazzo. Diseño estándar. Cintura elástica. Cierre de cordón.',
                'precio' => 24.99,
                'principalImg' => 'pantalones_niña6.webp',
                'img1' => 'pantalones_niña7.webp',
                'categoria_id' => 19,
            ],[
                'nombre' => 'Falda volantes estampada',
                'descripcion' => 'Summer camp. 100% algodón. Diseño tie-dye. Diseño corto. Diseño volantes. Cintura elástica. Sin cierre.',
                'precio' => 19.99,
                'principalImg' => 'falda_niña.webp',
                'img1' => 'falda_niña1.webp',
                'categoria_id' => 20, // ID de la categoría "Faldas" para niñas
            ],
            [
                'nombre' => 'Falda pantalón cruzada',
                'descripcion' => '100% algodón. Diseño falda pantalón. Diseño corto. Cintura elástica. Cierre de lazo. Tamaño mediano. Goma elástica. Diseño recto.',
                'precio' => 22.99,
                'principalImg' => 'falda_niña2.webp',
                'img1' => 'falda_niña3.webp',
                'categoria_id' => 20,
            ],
            [
                'nombre' => 'Falda estampada',
                'descripcion' => 'Estampado. Diseño corto. Diseño recto. Cierre de cremallera.',
                'precio' => 17.99,
                'principalImg' => 'falda_niña4.webp',
                'img1' => 'falda_niña5.webp',
                'categoria_id' => 20,
            ],
            [
                'nombre' => 'Falda textura flecos',
                'descripcion' => '100% Algodón. Con textura. Diseño corto. Diseño recto. Diseño cruzado. Flecos decorativos. Cierre de gancho. Cierre lateral de cremallera.',
                'precio' => 20.99,
                'principalImg' => 'falda_niña6.webp',
                'img1' => 'falda_niña7.webp',
                'categoria_id' => 20,
            ],[
                'nombre' => 'Bañador estampado tie-dye',
                'descripcion' => 'Summer camp. Colección baño. Estampado tie-dye. Estampado de rayas. Tirantes cruzados. Tirantes finos. Forro interior.',
                'precio' => 15.99,
                'principalImg' => 'bikini_niña.webp',
                'img1' => 'bikini_niña1.webp',
                'categoria_id' => 21, // ID de la categoría "Bikinis" para niñas
            ],
            [
                'nombre' => 'Bikini estampado',
                'descripcion' => 'Summer camp. Colección baño. Estampado. Braguita clásica. Cuello cuadrado. Tirantes finos.',
                'precio' => 17.99,
                'principalImg' => 'bikini_niña2.webp',
                'img1' => 'bikini_niña3.webp',
                'categoria_id' => 21,
            ],
            [
                'nombre' => 'Bañador rayas volante',
                'descripcion' => 'Summer camp. Colección baño. Estampado de rayas. Tirantes cruzados. Cuello redondo. Esta prenda también está disponible en la colección de Baby Girl..',
                'precio' => 14.99,
                'principalImg' => 'bikini_niña4.webp',
                'img1' => 'bikini_niña5.webp',
                'categoria_id' => 21,
            ],
            [
                'nombre' => 'Bañador asimétrico volante',
                'descripcion' => 'Diseño volantes. Con textura. Cuello asimétrico. Tirantes finos. Sin mangas. Forro interior. Esta prenda también está disponible en la colección de Baby Girl..',
                'precio' => 16.99,
                'principalImg' => 'bikini_niña6.webp',
                'img1' => 'bikini_niña7.webp',
                'categoria_id' => 21,
            ],[
                'nombre' => 'Camisa de Cuadros Azules',
                'descripcion' => 'Camisa de manga larga con diseño de cuadros en tonos azules.',
                'precio' => 22.99,
                'principalImg' => 'camisa_cuadros_azules.webp',
                'img1' => 'camisa_cuadros_azules1.webp',
                'categoria_id' => 22, // ID de la categoría "Camisas" para niños
            ],
            [
                'nombre' => 'Camisa de Rayas',
                'descripcion' => 'Camisa de manga corta con estampado de rayas blancas.',
                'precio' => 19.99,
                'principalImg' => 'camisa_rayas_niño.webp',
                'img1' => 'camisa_rayas_niño1.webp',
                'categoria_id' => 22,
            ],
            [
                'nombre' => 'Camisa estampados palmera',
                'descripcion' => 'Camisa estampados palmera azul porcelana.',
                'precio' => 25.99,
                'principalImg' => 'camisa_palmera.webp',
                'img1' => 'camisa_palmera1.webp',
                'categoria_id' => 22,
            ],
            [
                'nombre' => 'Camisa Blanca Clásica',
                'descripcion' => 'Camisa blanca de manga larga, ideal para ocasiones formales.',
                'precio' => 18.99,
                'principalImg' => 'camisa_blanca_clasica.webp',
                'img1' => 'camisa_blanca_clasica1.webp',
                'categoria_id' => 22,
            ],[
                'nombre' => 'Sudadera  Roja',
                'descripcion' => 'Sudadera roja.',
                'precio' => 29.99,
                'principalImg' => 'sudadera_roja.webp',
                'img1' => 'sudadera_roja1.webp',
                'categoria_id' => 23, // ID de la categoría "Sudaderas" para niños
            ],
            [
                'nombre' => 'Sudadera con Estampado de Pokemon',
                'descripcion' => 'Sudadera azul con capucha y estampado de pokemon en el frente y en la espalda. Con bolsillo de canguro en la parte delantera.',
                'precio' => 32.99,
                'principalImg' => 'sudadera_pokemon.webp',
                'img1' => 'sudadera_pokemon1.webp',
                'categoria_id' => 23,
            ],
            [
                'nombre' => 'Sudadera de Rayas ',
                'descripcion' => 'Sudadera sin capucha.',
                'precio' => 28.99,
                'principalImg' => 'sudadera_rayas.webp',
                'img1' => 'sudadera_rayas1.webp',
                'categoria_id' => 23,
            ],
            [
                'nombre' => 'Sudadera Negra Básica',
                'descripcion' => 'Sudadera negra con capucha, ideal para el día a día.',
                'precio' => 24.99,
                'principalImg' => 'sudadera_negra_basica.webp',
                'img1' => 'sudadera_negra_basica1.webp',
                'categoria_id' => 23,
            ],[
                'nombre' => 'Jersey de Algodón Gris',
                'descripcion' => 'Jersey de Algodón en color gris con cuello redondo.',
                'precio' => 34.99,
                'principalImg' => 'jersey_lana_gris.webp',
                'img1' => 'jersey_lana_gris1.webp',
                'categoria_id' => 24, // ID de la categoría "Jerséis" para niños
            ],
            [
                'nombre' => 'Jersey de Rayas Azules y Blancas',
                'descripcion' => 'Jersey de punto con rayas horizontales en azul y blanco.',
                'precio' => 31.99,
                'principalImg' => 'jersey_rayas_azules_blancas.webp',
                'img1' => 'jersey_rayas_azules_blancas1.webp',
                'categoria_id' => 24,
            ],
            [
                'nombre' => 'Jersey punto trenzado',
                'descripcion' => 'Jersey de punto trenzado y de color azul.',
                'precio' => 29.99,
                'principalImg' => 'jersey_punto_trenzado.webp',
                'img1' => 'jersey_punto_trenzado1.webp',
                'categoria_id' => 24,
            ],
            [
                'nombre' => 'Jersey de rallas horizontales',
                'descripcion' => 'Jersey de rallas azules con un color base crema',
                'precio' => 36.99,
                'principalImg' => 'jersey_rallas_horizontales.webp',
                'img1' => 'jersey_rallas_horizontales1.webp',
                'categoria_id' => 24,
            ],[
                'nombre' => 'Pantalones Vaqueros Azul Oscuro',
                'descripcion' => 'Pantalones vaqueros de corte recto en color azul oscuro.',
                'precio' => 27.99,
                'principalImg' => 'pantalones_vaqueros_azul_oscuro.webp',
                'img1' => 'pantalones_vaqueros_azul_oscuro1.webp',
                'categoria_id' => 25, // ID de la categoría "Pantalones" para niños
            ],
            [
                'nombre' => 'Pantalones largo verde',
                'descripcion' => 'Pantalones largo verde.',
                'precio' => 29.99,
                'principalImg' => 'pantalones_verde.webp',
                'img1' => 'pantalones_verde1.webp',
                'categoria_id' => 25,
            ],
            [
                'nombre' => 'Pantalones vaqueros elasticos',
                'descripcion' => 'Pantalones vaqueros con cintura elástica',
                'precio' => 24.99,
                'principalImg' => 'pantalones_elastica.webp',
                'img1' => 'pantalones_elastica1.webp',
                'categoria_id' => 25,
            ],
            [
                'nombre' => 'Pantalón de niño liso chino',
                'descripcion' => 'Pantalón de niño liso chino de color camel.',
                'precio' => 21.99,
                'principalImg' => 'pantalones_niño_liso.webp',
                'img1' => 'pantalones_niño_liso1.webp',
                'categoria_id' => 25,
            ],[
                'nombre' => 'Anorak acolchado',
                'descripcion' => 'Anorak de color azul oscuro con cremallera.',
                'precio' => 59.99,
                'principalImg' => 'anorak_acolchado.webp',
                'img1' => 'anorak_acolchado1.webp',
                'categoria_id' => 26, // ID de la categoría "Abrigos" para niños
            ],
            [
                'nombre' => 'Chaqueta Vaquera Clásica',
                'descripcion' => 'Chaqueta vaquera en azul claro con botones metálicos.',
                'precio' => 49.99,
                'principalImg' => 'chaqueta_vaquera_clasica.webp',
                'img1' => 'chaqueta_vaquera_clasica1.webp',
                'categoria_id' => 26,
            ],
            [
                'nombre' => 'Anorak capucha pelo',
                'descripcion' => 'Anorak capucha pelo con bolsillo delateros y cremallerasa',
                'precio' => 64.99,
                'principalImg' => 'anorak_capucha_pelo.webp',
                'img1' => 'anorak_capucha_pelo1.webp',
                'categoria_id' => 26,
            ],
            [
                'nombre' => 'Parka capucha',
                'descripcion' => 'Parka con capucha de color marrón.',
                'precio' => 69.99,
                'principalImg' => 'parka_capucha.webp',
                'img1' => 'parka_capucha1.webp',
                'categoria_id' => 26,
            ],[
                'nombre' => 'Bañador de Rayas Azul y Blanco',
                'descripcion' => 'Bañador con diseño de rayas en azul y blanco.',
                'precio' => 19.99,
                'principalImg' => 'banador_rayas_azul_blanco.webp',
                'img1' => 'banador_rayas_azul_blanco1.webp',
                'categoria_id' => 27, // ID de la categoría "Bañadores" para niños
            ],
            [
                'nombre' => 'Bañador de zig-zag',
                'descripcion' => 'Bañador azul con estampado de zig-zag y cintura ajustable.',
                'precio' => 21.99,
                'principalImg' => 'banador_zig-zag.webp',
                'img1' => 'banador_zig-zag1.webp',
                'categoria_id' => 27,
            ],
            [
                'nombre' => 'Bañador estampado langostas',
                'descripcion' => 'Bañador con estampados de langostas azul turquesa.',
                'precio' => 17.99,
                'principalImg' => 'banador_langostas.webp',
                'img1' => 'banador_langostas1.webp',
                'categoria_id' => 27,
            ],
            [
                'nombre' => 'Bañador de Rayas',
                'descripcion' => 'Bañador con diseño de rayas de color blanco.',
                'precio' => 22.99,
                'principalImg' => 'banador_rayas.webp',
                'img1' => 'banador_rayas1.webp',
                'categoria_id' => 27,
            ],[
                'nombre' => 'Abrigo negro ovalo',
                'descripcion' => 'Forma ovalada y punto neopreno sin forro: el combo ideal para este abrigo negro estructurado.',
                'precio' => 79.99,
                'principalImg' => 'abrigo_chica.webp',
                'img1' => 'abrigo_chica1.webp',
                'categoria_id' => 28, // ID de la categoría "Abrigos" para mujeres
            ],
            [
                'nombre' => 'Abrigo recto solapas',
                'descripcion' => 'Colección fiesta y ceremonia. Estructura pesada. Diseño medio. Tejido de lana. Diseño recto. Diseño largo. Diseño oversize. Cuello pico con solapa. Dos bolsillos de solapa. Manga larga. Cierre de botones.',
                'precio' => 89.99,
                'principalImg' => 'abrigo_chica2.webp',
                'img1' => 'abrigo_chica3.webp',
                'categoria_id' => 28,
            ],
            [
                'nombre' => 'Abrigo pelo solapas',
                'descripcion' => 'Colección fiesta y ceremonia. Tejido de pelo. Diseño recto. Manga larga. Cierre de botones.',
                'precio' => 99.99,
                'principalImg' => 'abrigo_chica4.webp',
                'img1' => 'abrigo_chica5.webp',
                'categoria_id' => 28,
            ],
            [
                'nombre' => 'Trench doble botonadura',
                'descripcion' => 'Tejido de algodón. Tejido poliéster. Diseño largo. Diseño recto. Cuello camisero. Cierre de cuerda. Cierre delantero. Cinturón ajustable. Dos bolsillos de solapa. Cierre de botones.',
                'precio' => 69.99,
                'principalImg' => 'abrigo_chica6.webp',
                'img1' => 'abrigo_chica7.webp',
                'categoria_id' => 28,
            ],[
                'nombre' => 'Blusa blanco roto',
                'descripcion' => 'Bordados dorados en forma de espiga, crepé marroquí arrugado y botones nacarados. Repleta de detalles ultrafemeninos, esta blusa es un must-have del verano.',
                'precio' => 34.99,
                'principalImg' => 'blusa_chica.webp',
                'img1' => 'blusa_chica1.webp',
                'categoria_id' => 29, // ID de la categoría "Blusas y camisas" para mujeres
            ],
            [
                'nombre' => 'Camisa tirantes cropped',
                'descripcion' => 'Camiseta tirantes blanco roto cropped niña,Cuello redondo, manga corta,Punto acanalado, print mensaje vintage',
                'precio' => 39.99,
                'principalImg' => 'blusa_chica2.webp',
                'img1' => 'blusa_chica3.webp',
                'categoria_id' => 29,
            ],
            [
                'nombre' => 'Camisa rosa mensaje',
                'descripcion' => 'Camiseta rosa fluo niña, Cuello redondo, manga corta, Print mensajes purpurina dorada o rosa fluo',
                'precio' => 49.99,
                'principalImg' => 'blusa_chica4.webp',
                'img1' => 'blusa_chica5.webp',
                'categoria_id' => 29,
            ],
            [
                'nombre' => 'Camisa blanco rot sol rosa',
                'descripcion' => 'Camiseta blanco roto niña.Cuello redondo, manga corta.Maxi sol sonriente rosa y mensaje naranja fluo delante',
                'precio' => 29.99,
                'principalImg' => 'blusa_chica6.webp',
                'img1' => 'blusa_chica7.webp',
                'categoria_id' => 29,
            ],[
                'nombre' => 'Pantalones Palazzo Negros',
                'descripcion' => 'Pantalones palazzo de tiro alto en color negro con pierna ancha.',
                'precio' => 49.99,
                'principalImg' => 'pantalones_palazzo_negros.webp',
                'img1' => 'pantalones_palazzo_negros1.webp',
                'categoria_id' => 9, // ID de la categoría "Pantalones" para mujeres
            ],
            [
                'nombre' => 'Pantalones de Cuero Sintético',
                'descripcion' => 'Pantalones ajustados de cuero sintético en color marrón.',
                'precio' => 54.99,
                'principalImg' => 'pantalones_cuero_sintetico.webp',
                'img1' => 'pantalones_cuero_sintetico1.webp',
                'categoria_id' => 9,
            ],
            [
                'nombre' => 'Pantalones Cargo Verde Oliva',
                'descripcion' => 'Pantalones cargo en tono verde oliva con múltiples bolsillos.',
                'precio' => 44.99,
                'principalImg' => 'pantalones_cargo_verde_oliva.webp',
                'img1' => 'pantalones_cargo_verde_oliva1.webp',
                'categoria_id' => 9,
            ],[
                'nombre' => 'Pantalón estampado geométrico',
                'descripcion' => 'Tejido 100% algodón. Estampado geométrico de colores. Diseño largo. Diseño recto. Cintura elástica. Sin cierre.',
                'precio' => 39.99,
                'principalImg' => 'pantalones_chica.webp',
                'img1' => 'pantalones_chica1.webp',
                'categoria_id'=> 30,
            ],

            [
                'nombre' => 'Pantalón rayas multicolor',
                'descripcion' => 'Tejido fluido. Estampado de rayas. Diseño multicolor. Diseño largo. Diseño recto. Cintura elástica. Cierre de cordón.',
                'precio' => 49.99,
                'principalImg' => 'pantalones_chica2.webp',
                'img1' => 'pantalones_chica3.webp',
                'categoria_id' => 30, // ID de la categoría "Pantalones" para mujeres
            ],
            [
                'nombre' => 'Pantalón recto lino',
                'descripcion' => 'Tejido mezcla de algodón y lino. Diseño largo. Diseño recto. Dos bolsillos de solapa. Cintura elástica. Cierre de cordón.',
                'precio' => 54.99,
                'principalImg' => 'pantalones_chica4.webp',
                'img1' => 'pantalones_chica5.webp',
                'categoria_id' => 30,
            ],
            [
                'nombre' => 'Pantalón estampado lazo',
                'descripcion' => 'Conjunto. Total look. Estampado. Diseño largo. Regular fit. Cintura elástica. Cierre de cordón.',
                'precio' => 44.99,
                'principalImg' => 'pantalones_chica6.webp',
                'img1' => 'pantalones_chica7.webp',
                'categoria_id' => 30,
            ],
            
            [
                'nombre' => 'Vestido punto midi multicolor',
                'descripcion' => 'Tejido de punto fino. Diseño multicolor. Diseño midi. Diseño ajustado. Cuello redondo. Tirantes anchos.',
                'precio' => 59.99,
                'principalImg' => 'vestido_chica.webp',
                'img1' => 'vestido_chica1.webp',
                'categoria_id' => 31, // ID de la categoría "Vestidos" para mujeres
            ],
            [
                'nombre' => 'Vestido estampado volantes',
                'descripcion' => 'Colección Baño. Tejido de viscosa. Diseño recto. Cuello pico. Tirantes finos. Volantes en el bajo. Sin mangas. Forro interior de algodón. Sin cierre.',
                'precio' => 79.99,
                'principalImg' => 'vestido_chica2.webp',
                'img1' => 'vestido_chica3.webp',
                'categoria_id' => 31,
                ],
                [
                'nombre' => 'Vestido estampado tie-dye',
                'descripcion' => 'Estampado tie-dye. Diseño largo. Diseño acampanado. Tirantes finos. Escote de pico con cierre de cordón. Aberturas decorativas. Volantes en el bajo.',
                'precio' => 69.99,
                'principalImg' => 'vestido_chica4.webp',
                'img1' => 'vestido_chica5.webp',
                'categoria_id' => 31,
                ],
                [
                'nombre' => 'Vestido fruncido volantes',
                'descripcion' => 'Colección Baño. Tejido de algodón. Diseño largo. Diseño volantes. Detalle fruncido. Tirantes finos. Sin cierre.',
                'precio' => 49.99,
                'principalImg' => 'vestido_chica6.webp',
                'img1' => 'vestido_chica7.webp',
                'categoria_id' => 31,
                ],[
                'nombre' => 'Chaleco lúrex calado',
                'descripcion' => 'Tejido de punto calado. Tejido de viscosa. Diseño recto. Diseño largo. Lúrex. Cuello pico. Cierre delantero.',
                'precio' => 39.99,
                'principalImg' => 'chaleco_chica.webp',
                'img1' => 'chaleco_chica1.webp',
                'categoria_id' => 32, // ID de la categoría "Chalecos" para mujeres
                ],
                [
                'nombre' => 'Chaleco halter lino',
                'descripcion' => 'Tejido mezcla de algodón y lino. Abertura en la espalda. Diseño halter. Cuello pico. Diseño crop. Dos bolsillos de ribete laterales. Cierre delantero. Cierre de botones.',
                'precio' => 29.99,
                'principalImg' => 'chaleco_chica2.webp',
                'img1' => 'chaleco_chica3.webp',
                'categoria_id' => 32,
                ],
                [
                'nombre' => 'Chaleco lino botones',
                'descripcion' => 'Tejido mezcla de algodón y lino. Diseño recto. Diseño crop. Cuello pico. Sin mangas. Cierre de botones. Cierre delantero.',
                'precio' => 34.99,
                'principalImg' => 'chaleco_chica4.webp',
                'img1' => 'chaleco_chica5.webp',
                'categoria_id' => 32,
                ],
                [
                'nombre' => 'Chaleco crop estampado',
                'descripcion' => 'Tejido mezcla de algodón y lino. Diseño crop. Estampado. Cuello pico. Sin mangas. Cierre de botones.',
                'precio' => 49.99,
                'principalImg' => 'chaleco_chica6.webp',
                'img1' => 'chaleco_chica7.webp',
                'categoria_id' => 32,
                ],[
                'nombre' => 'Falda estampado abalorios',
                'descripcion' => 'Estampado étnico. Detalle de abalorios. Diseño acampanado. Diseño corto. Detalle de volante. Cintura elástica.',
                'precio' => 34.99,
                'principalImg' => 'falda_chica.webp',
                'img1' => 'falda_chica1.webp',
                'categoria_id' => 33, // ID de la categoría "Faldas" para mujeres
                ],
                [
                'nombre' => 'Falda lino lazo',
                'descripcion' => 'Tejido de lino. Diseño recto. Diseño largo. Cintura elástica. Cierre de lazo.',
                'precio' => 39.99,
                'principalImg'=> 'falda_chica2.webp',
                'img1' => 'falda_chica3.webp',
                'categoria_id' => 33,
                ],[
                'nombre' => 'Falda midi estampada',
                'descripcion' => 'Conjunto. Total look. Tejido de viscosa. Diseño recto. Diseño midi. Estampada. Cintura elástica. Cierre de cordón.',
                'precio' => 49.99,
                'principalImg' => 'falda_chica4.webp',
                'img1' => 'falda_chica5.webp',
                'categoria_id' => 33,
                ],
                [
                'nombre' => 'Falda lino lazo',
                'descripcion' => 'Tejido de lino. Diseño recto. Diseño largo. Cintura elástica. Cierre de lazo.',
                'precio' => 44.99,
                'principalImg' => 'falda_chica6.webp',
                'img1' => 'falda_chica7.webp',
                'categoria_id' => 33,
                ],[
                'nombre' => 'Bañador detalle abertura',
                'descripcion' => 'Estampado de rayas. Acabado brillante. Palabra de honor. Aberturas decorativas. Foam extraíble.',
                'precio' => 39.99,
                'principalImg' => 'bikini_chica.webp',
                'img1' => 'bikini_chica1.webp',
                'categoria_id' => 34, // ID de la categoría "Bikinis" para mujeres
                ],
                [
                'nombre' => 'Bikini asimétrico lurex',
                'descripcion' => 'Colección baño. Tejido de lúrex. Braguita clásica. Cintura elástica. Foam extraíble. Sin cierre.',
                'precio' => 34.99,
                'principalImg' => 'bikini_chica2.webp',
                'img1' => 'bikini_chica3.webp',
                'categoria_id' => 34,
                ],
                [
                'nombre' => 'Bikini estampado asimétrico',
                'descripcion' => 'ejido elástico. Estampado tie-dye. Detalles fruncidos. Top asimétrico. Tirante ancho. Relleno de foam. Braguita clásica. Sin cierre.',
                'precio' => 37.99,
                'principalImg' => 'bikini_chica4.webp',
                'img1' => 'bikini_chica5.webp',
                'categoria_id' => 34,
                ],
                [
                'nombre' => 'Bikini textura',
                'descripcion' => 'ejido elástico. Tejido con textura. Braguita clásica. Escote redondo. Tirante fino. Cierre de lazo. Relleno de foam. Foam extraíble.',
                'precio' => 42.99,
                'principalImg' => 'bikini_chica6.webp',
                'img1' => 'bikini_chica7.webp',
                'categoria_id' => 34,
                ],
                [
                'nombre' => 'Top bandeau fruncido',
                'descripcion' => 'Tejido de algodón. Diseño bandeau. Fruncido elástico. Slim fit. Sin mangas.',
                'precio' => 24.99,
                'principalImg' => 'top_chica.webp',
                'img1' => 'top_chica1.webp',
                'categoria_id' => 35, // ID de la categoría "Tops" para mujeres
                ],
                [
                'nombre' => 'Top acabado brillante',
                'descripcion' => 'Diseño recto. Diseño crop. Tirantes anchos. Detalle de abertura. Punto medio. Cuello pico. Sin mangas. Cierre de lazo ajustable.',
                'precio' => 29.99,
                'principalImg' => 'top_chica2.webp',
                'img1' => 'top_chica3.webp',
                'categoria_id' => 35,
                ],
                [
                'nombre' => 'Top bandeau fruncido',
                'descripcion' => 'Tejido de algodón. Estampado. Diseño volantes. Detalle brillante. Terminaciones elásticas. Sin mangas. Sin cierre.',
                'precio' => 27.99,
                'principalImg' => 'top_chica4.webp',
                'img1' => 'top_chica5.webp',
                'categoria_id' => 35,
                ],
                [
                'nombre' => 'Top acabado brillante',
                'descripcion' => 'Diseño recto. Diseño crop. Tirantes anchos. Detalle de abertura. Punto medio. Cuello pico. Sin mangas. Cierre de lazo ajustable.',
                'precio' => 32.99,
                'principalImg' => 'top_chica6.webp',
                'img1' => 'top_chica7.webp',
                'categoria_id' => 35,
                ],[
                    "nombre"=> "Camisa vestir regular fit rayas",
                    "descripcion"=> "Colección fiesta y ceremonia. Tejido de algodón. Regular fit. Cuello camisero. Puños abotonados. Manga larga. Cierre delantero.",
                    "precio"=> 39.99,
                    "principalImg"=> "camisa_chico.webp",
                    "img1"=> "camisa_chico1.webp",
                    "categoria_id"=> 36,
                ],[
                    'nombre' => 'Camisa lino rayas',
                    'descripcion' => 'Tejido mezcla de algodón y lino. Regular fit. Estampado de rayas. Cuello camisero. Manga larga. Cierre delantero. Cierre de botones.',
                    'precio' => 49.99,
                    'principalImg' => 'camisa_chico2.webp',
                    'img1' => 'camisa_chico3.webp',
                    'categoria_id' => 36,
                ],
                [
                    'nombre' => 'Camisa oxford unisex',
                    'descripcion' => 'Unisex. 100% algodón. Diseño recto. Regular fit. Estilo Oxford. Cuello camisero. Puños abotonados. Manga larga. Cierre delantero. Cierre de botones.',
                    'precio' => 59.99,
                    'principalImg' => 'camisa_chico4.webp',
                    'img1' => 'camisa_chico5.webp',
                    'categoria_id' => 36,
                ],
                [
                    'nombre' => 'Camisa regular fit algodón',
                    'descripcion' => 'Cuello camisero. Manga larga. Tejido ligero. Regular fit. Cierre delantero.',
                    'precio' => 44.99,
                    'principalImg' => 'camisa_chico6.webp',
                    'img1' => 'camisa_chico7.webp',
                    'categoria_id' => 36,
                ],[
                    'nombre' => 'Sudadera algodón',
                    'descripcion' => '100% algodón. Diseño recto. Regular fit. Cuello redondo. Manga larga. Sin cierre.',
                    'precio' => 39.99,
                    'principalImg' => 'sudadera_chico.webp',
                    'img1' => 'sudadera_chico1.webp',
                    'categoria_id' => 37, // ID de la categoría "Sudaderas" para hombres
                ],
                [
                    'nombre' => 'Sudadera estampada posterior',
                    'descripcion' => 'Tejido mezcla de algodón. Tejido ligero. Regular fit. Cuello redondo. Manga larga. Sin cierre. Diseño estampado en la parte posterior. Detalle bordado.',
                    'precio' => 44.99,
                    'principalImg' => 'sudadera_chico2.webp',
                    'img1' => 'sudadera_chico3.webp',
                    'categoria_id' => 37,
                ],
                [
                    'nombre' => 'Sudadera capucha unisex',
                    'descripcion' => 'Unisex. 100% algodón. Diseño recto. Bolsillo canguro. Capucha. Manga larga. Sin cierre.',
                    'precio' => 49.99,
                    'principalImg' => 'sudadera_chico4.webp',
                    'img1' => 'sudadera_chico5.webp',
                    'categoria_id' => 37,
                ],
                [
                    'nombre' => 'Sudadera algodón',
                    'descripcion' => '100% algodón. Diseño recto. Regular fit. Cuello redondo. Manga larga. Sin cierre.',
                    'precio' => 54.99,
                    'principalImg' => 'sudadera_chico6.webp',
                    'img1' => 'sudadera_chico7.webp',
                    'categoria_id' => 37,
                ],[
                    'nombre' => 'Chaleco acolchado',
                    'descripcion' => 'Diseño acolchado. Diseño recto. Dos bolsillos de solapa. Sin mangas. Dos bolsillos de solapa laterales. Cierre de cremallera.',
                    'precio' => 149.99,
                    'principalImg' => 'chaleco_chico.webp',
                    'img1' => 'chaleco_chico1.webp',
                    'categoria_id' => 38, // ID de la categoría "Chaquetas" para hombres
                ],
                [
                    'nombre' => 'Chaleco acolchado',
                    'descripcion' => 'Diseño acolchado. Diseño largo. Diseño recto. Con capucha. Dos bolsillos de cremallera. Sin mangas. Cierre de cremallera.',
                    'precio' => 99.99,
                    'principalImg' => 'chaleco_chico2.webp',
                    'img1' => 'chaleco_chico3.webp',
                    'categoria_id' => 38,
                ],
                [
                    'nombre' => 'Anorak acolchado cremallera',
                    'descripcion' => 'Tejido de poliamida, diseño acolchado, diseño recto, cuello redondo, tejido ligero, manga larga, cierre delantero, con relleno, cierre de cremallera, diseño estándar, diseño recto.',
                    'precio' => 79.99,
                    'principalImg' => 'chaleco_chico4.webp',
                    'img1' => 'chaleco_chico5.webp',
                    'categoria_id' => 38,
                ],
                [
                    'nombre' => 'Bomber algodón',
                    'descripcion' => '100% algodón. Diseño bomber. Diseño recto. Cuello redondo. Manga larga. Cierre delantero. Cierre de cremallera.',
                    'precio' => 119.99,
                    'principalImg' => 'chaleco_chico6.webp',
                    'img1' => 'chaleco_chico7.webp',
                    'categoria_id' => 38,

                ],['nombre' => 'Pantalón cargo algodón',
                    'descripcion' => 'Tejido de algodón. Diseño cargo. Tiro medio. Dos bolsillos cargo. Cierre de cremallera y botón.',
                    'precio' => 49.99,
                    'principalImg' => 'pantalon_chico.webp',
                    'img1' => 'pantalon_chico1.webp',
                    'categoria_id' => 39, // ID de la categoría "Pantalones" para hombres
                ],[
                    'nombre' => 'Pantalón chino algodón',
                    'descripcion' => 'Tejido de algodón. Estilo chinos. Diseño recto. Diseño largo. Dos bolsillos. Bolsillo de ribete.',
                    'precio' => 59.99,
                    'principalImg' => 'pantalon_chico2.webp',
                    'img1' => 'pantalon_chico3.webp',
                    'categoria_id' => 39,
                    ],
                [
                    'nombre' => 'Pantalón jogger algodón',
                    'descripcion' => 'Tejido de algodón. Diseño recto. Diseño largo. Diseño jogger. Dos bolsillos de solapa. Cintura elástica. Cierre de cordón.',
                    'precio' => 54.99,
                    'principalImg' => 'pantalon_chico4.webp',
                    'img1' => 'pantalon_chico5.webp',
                    'categoria_id' => 39,
                ],
                [
                    'nombre' => 'Pantalón recto cintura elástica',
                    'descripcion' => 'Tejido con algodón. Diseño recto. Diseño largo. Cintura elástica con cordón. Dos bolsillos de parche en la parte posterior.',
                    'precio' => 39.99,
                    'principalImg' => 'pantalon_chico6.webp',
                    'img1' => 'pantalon_chico7.webp',
                    'categoria_id' => 39,
                ],[
                    'nombre' => 'Bañador estampado hojas',
                    'descripcion' => 'Estampado de hojas. Diseño recto. Diseño corto. Cintura elástica. Cierre de cordón. Dos bolsillos laterales. Bolsillo de parche en la parte posterior.',
                    'precio' => 29.99,
                    'principalImg' => 'banador_chico.webp',
                    'img1' => 'banador_chico1.webp',
                    'categoria_id' => 40, // ID de la categoría "Bañadores" para hombres
                ],
                [
                    'nombre' => 'Bañador estampado marino',
                    'descripcion' => 'Estampado marino. Diseño corto. Cintura elástica con cordón ajustable. Dos bolsillos laterales. Bolsillo de parche en la parte posterior.',
                    'precio' => 34.99,
                    'principalImg' => 'banador_chico2.webp',
                    'img1' => 'banador_chico3.webp',
                    'categoria_id' => 40,
                ],
                [
                    'nombre' => 'Bañador básico cordón',
                    'descripcion' => 'Diseño básico. Dos bolsillos de solapa. Bolsillo de parche. Cierre de cordón.',
                    'precio' => 39.99,
                    'principalImg' => 'banador_chico4.webp',
                    'img1' => 'banador_chico5.webp',
                    'categoria_id' => 40,
                ],
                [
                    'nombre' => 'Bañador estampado',
                    'descripcion' => 'Estampado geométrico. Diseño recto. Diseño corto. Cintura elástica. Cierre de cordón. Dos bolsillos laterales. Bolsillo de parche en la parte posterior.',
                    'precio' => 44.99,
                    'principalImg' => 'banador_chico6.webp',
                    'img1' => 'banador_chico7.webp',
                    'categoria_id' => 40,
                ],
                [
                    'nombre' => 'Atuendo casual 1',
                    'descripcion' => 'Descripción del atuendo casual 1 para Primavera',
                    'precio' => 50.99,
                    'principalImg' => 'imagen1_primavera.webp',
                    'img1' => 'imagen2_primavera.webp',
                    'categoria_id' => 41,
                ],
                [
                    'nombre' => 'Atuendo casual 2',
                    'descripcion' => 'Descripción del atuendo casual 2 para Primavera',
                    'precio' => 45.99,
                    'principalImg' => 'imagen3_primavera.webp',
                    'img1' => 'imagen4_primavera.webp',
                    'categoria_id' => 41,
                ],
                [
                    'nombre' => 'Atuendo casual 3',
                    'descripcion' => 'Descripción del atuendo casual 3 para Primavera',
                    'precio' => 55.99,
                    'principalImg' => 'imagen5_primavera.webp',
                    'img1' => 'imagen6_primavera.webp',
                    'categoria_id' => 41,
                ],
                [
                    'nombre' => 'Atuendo casual 4',
                    'descripcion' => 'Descripción del atuendo casual 4 para Primavera',
                    'precio' => 60.99,
                    'principalImg' => 'imagen8_primavera.webp',
                    'img1' => 'imagen7_primavera.webp',
                    'categoria_id' => 41,
                ],
                [
                    'nombre' => 'Vestido Primavera 1',
                    'descripcion' => 'Descripción del vestido 1 para Primavera',
                    'precio' => 69.99,
                    'principalImg' => 'vestido_primavera1.webp',
                    'img1' => 'vestido_primavera1_2.webp',
                    'categoria_id' => 42,
                ],
                [
                    'nombre' => 'Vestido Primavera 2',
                    'descripcion' => 'Descripción del vestido 2 para Primavera',
                    'precio' => 79.99,
                    'principalImg' => 'vestido_primavera2.webp',
                    'img1' => 'vestido_primavera2_2.webp',
                    'categoria_id' => 42,
                ],
                [
                    'nombre' => 'Vestido Primavera 3',
                    'descripcion' => 'Descripción del vestido 3 para Primavera',
                    'precio' => 89.99,
                    'principalImg' => 'vestido_primavera3.webp',
                    'img1' => 'vestido_primavera3_2.webp',
                    'categoria_id' => 42,
                ],
                [
                    'nombre' => 'Vestido Primavera 4',
                    'descripcion' => 'Descripción del vestido 4 para Primavera',
                    'precio' => 99.99,
                    'principalImg' => 'vestido_primavera4.webp',
                    'img1' => 'vestido_primavera4_2.webp',
                    'categoria_id' => 42,
                ],[
                    'nombre' => 'Collar Primavera',
                    'descripcion' => 'Descripción del collar para Primavera',
                    'precio' => 29.99,
                    'principalImg' => 'collar_primavera.webp',
                    'img1' => 'collar_primavera_2.webp',
                    'categoria_id' => 43, // Asegúrate de que el ID de la categoría "Accesorios" sea correcto
                ],
                [
                    'nombre' => 'Pulseras Primavera',
                    'descripcion' => 'Descripción de las pulseras para Primavera',
                    'precio' => 19.99,
                    'principalImg' => 'pulseras_primavera.webp',
                    'img1' => 'pulseras_primavera_2.webp',
                    'categoria_id' => 43,
                ],
                [
                    'nombre' => 'Bolsa Primavera',
                    'descripcion' => 'Descripción de la bolsa para Primavera',
                    'precio' => 39.99,
                    'principalImg' => 'bolsa_primavera.webp',
                    'img1' => 'bolsa_primavera_2.webp',
                    'categoria_id' => 43,
                ],
                [
                    'nombre' => 'Gafas de sol Primavera',
                    'descripcion' => 'Descripción de las gafas de sol para Primavera',
                    'precio' => 49.99,
                    'principalImg' => 'gafas_primavera.webp',
                    'img1' => 'gafas_primavera_2.webp',
                    'categoria_id' => 43,
                ],[
                    'nombre' => 'Traje de baño Verano 1',
                    'descripcion' => 'Descripción del traje de baño 1 para Verano',
                    'precio' => 39.99,
                    'principalImg' => 'traje_bano_verano_1.webp',
                    'img1' => 'traje_bano_verano_1_2.webp',
                    'categoria_id' => 44,
                ],
                [
                    'nombre' => 'Traje de baño Verano 2',
                    'descripcion' => 'Descripción del traje de baño 2 para Verano',
                    'precio' => 49.99,
                    'principalImg' => 'traje_bano_verano_2.webp',
                    'img1' => 'traje_bano_verano_2_2.webp',
                    'categoria_id' => 44,
                ],
                [
                    'nombre' => 'Traje de baño Verano 3',
                    'descripcion' => 'Descripción del traje de baño 3 para Verano',
                    'precio' => 59.99,
                    'principalImg' => 'traje_bano_verano_3.webp',
                    'img1' => 'traje_bano_verano_3_2.webp',
                    'categoria_id' => 44,
                ],
                [
                    'nombre' => 'Traje de baño Verano 4',
                    'descripcion' => 'Descripción del traje de baño 4 para Verano',
                    'precio' => 69.99,
                    'principalImg' => 'traje_bano_verano_4.webp',
                    'img1' => 'traje_bano_verano_4_2.webp',
                    'categoria_id' => 44,
                ],[
                    'nombre' => 'Conjunto deportivo Verano 1',
                    'descripcion' => 'Descripción del conjunto deportivo 1 para Verano',
                    'precio' => 49.99,
                    'principalImg' => 'deportivo_verano_1.webp',
                    'img1' => 'deportivo_verano_1_2.webp',
                    'categoria_id' => 45, // Asegúrate de que el ID de la categoría "Ropa deportiva" sea correcto
                ],
                [
                    'nombre' => 'Conjunto deportivo Verano 2',
                    'descripcion' => 'Descripción del conjunto deportivo 2 para Verano',
                    'precio' => 59.99,
                    'principalImg' => 'deportivo_verano_2.webp',
                    'img1' => 'deportivo_verano_2_2.webp',
                    'categoria_id' => 45,
                ],
                [
                    'nombre' => 'Conjunto deportivo Verano 3',
                    'descripcion' => 'Descripción del conjunto deportivo 3 para Verano',
                    'precio' => 29.99,
                    'principalImg' => 'deportiva_verano.webp',
                    'img1' => 'deportiva_verano_2.webp',
                    'categoria_id' => 45,
                ],
                [
                    'nombre' => 'Conjunto deportivo Verano 4',
                    'descripcion' => 'Descripción del conjunto deportivo 4 para Verano',
                    'precio' => 24.99,
                    'principalImg' => 'deportivo_verano23.webp',
                    'img1' => 'deportivo_verano_23.webp',
                    'categoria_id' => 45,
                ],[
                    'nombre' => 'Gorra Verano',
                    'descripcion' => 'Descripción de la gorra para Verano',
                    'precio' => 19.99,
                    'principalImg' => 'gorra_verano.webp',
                    'img1' => 'gorra_verano_2.webp',
                    'categoria_id' => 46, // Asegúrate de que el ID de la categoría "Accesorios" sea correcto
                ],
                [
                    'nombre' => 'Lentes de sol Verano',
                    'descripcion' => 'Descripción de los lentes de sol para Verano',
                    'precio' => 29.99,
                    'principalImg' => 'lentes_sol_verano.webp',
                    'img1' => 'lentes_sol_verano_2.webp',
                    'categoria_id' => 46,
                ],
                [
                    'nombre' => 'Sombrero Verano',
                    'descripcion' => 'Descripción del sombrero para Verano',
                    'precio' => 24.99,
                    'principalImg' => 'sombrero_verano.webp',
                    'img1' => 'sombrero_verano_2.webp',
                    'categoria_id' => 46,
                ],
                [
                    'nombre' => 'Bolsa de playa Verano',
                    'descripcion' => 'Descripción de la bolsa de playa para Verano',
                    'precio' => 39.99,
                    'principalImg' => 'bolsa_playa_verano.webp',
                    'img1' => 'bolsa_playa_verano_2.webp',
                    'categoria_id' => 46,
                ],[
                    'nombre' => 'Jersey Otoño',
                    'descripcion' => 'Descripción del jersey para Otoño',
                    'precio' => 49.99,
                    'principalImg' => 'jersey_otono.webp',
                    'img1' => 'jersey_otono_2.webp',
                    'categoria_id' => 47, // Asegúrate de que el ID de la categoría "Prendas de punto" sea correcto
                ],
                [
                    'nombre' => 'Chaleco Otoño',
                    'descripcion' => 'Descripción del chaleco para Otoño',
                    'precio' => 39.99,
                    'principalImg' => 'chaleco_otono.webp',
                    'img1' => 'chaleco_otono_2.webp',
                    'categoria_id' => 47,
                ],
                [
                    'nombre' => 'Bufanda Otoño',
                    'descripcion' => 'Descripción de la bufanda para Otoño',
                    'precio' => 19.99,
                    'principalImg' => 'bufanda_otono.webp',
                    'img1' => 'bufanda_otono_2.webp',
                    'categoria_id' => 47,
                ],
                [
                    'nombre' => 'Guantes Otoño',
                    'descripcion' => 'Descripción de los guantes para Otoño',
                    'precio' => 14.99,
                    'principalImg' => 'guantes_otono.webp',
                    'img1' => 'guantes_otono_2.webp',
                    'categoria_id' => 47,
                ],[
                    'nombre' => 'Chaqueta Entretiempo 1',
                    'descripcion' => 'Descripción de la chaqueta para entretiempo',
                    'precio' => 89.99,
                    'principalImg' => 'Chaqueta1.webp',
                    'img1' => 'Chaqueta2.webp',
                    'categoria_id' => 48, // Asegúrate de que el ID de la categoría "Prendas de entretiempo" sea correcto
                ],
                [
                    'nombre' => 'Chaqueta Entretiempo 2',
                    'descripcion' => 'Descripción de la chaqueta para entretiempo',
                    'precio' => 79.99,
                    'principalImg' => 'chaqueta_entretiempo.webp',
                    'img1' => 'chaqueta_entretiempo_2.webp',
                    'categoria_id' => 48,
                ],
                [
                    'nombre' => 'Chaleco Entretiempo 3',
                    'descripcion' => 'Descripción del chaleco para entretiempo',
                    'precio' => 59.99,
                    'principalImg' => 'chaleco_entretiempo3.webp',
                    'img1' => 'chaleco_entretiempo_4.webp',
                    'categoria_id' => 48,
                ],
                [
                    'nombre' => 'Chaleco Entretiempo 4',
                    'descripcion' => 'Descripción del chaleco para entretiempo',
                    'precio' => 49.99,
                    'principalImg' => 'sudadera_entretiempo.webp',
                    'img1' => 'sudadera_entretiempo_2.webp',
                    'categoria_id' => 48,
                ],[
                    'nombre' => 'Calzado Otoño 1',
                    'descripcion' => 'Descripción de las botas para Otoño',
                    'precio' => 79.99,
                    'principalImg' => 'botas_otono.webp',
                    'img1' => 'botas_otono_2.webp',
                    'categoria_id' => 49, // Asegúrate de que el ID de la categoría "Calzado de temporada" sea correcto
                ],
                [
                    'nombre' => 'Calzado Otoño 2',
                    'descripcion' => 'Descripción de los zapatos para Otoño',
                    'precio' => 69.99,
                    'principalImg' => 'zapatos_otono.webp',
                    'img1' => 'zapatos_otono_2.webp',
                    'categoria_id' => 49,
                ],
                [
                    'nombre' => 'Calzado Otoño 3',
                    'descripcion' => 'Descripción de las zapatillas para Otoño',
                    'precio' => 59.99,
                    'principalImg' => 'zapatillas_otono.webp',
                    'img1' => 'zapatillas_otono_2.webp',
                    'categoria_id' => 49,
                ],
                [
                    'nombre' => 'Calzado Otoño 4',
                    'descripcion' => 'Descripción de los botines para Otoño',
                    'precio' => 89.99,
                    'principalImg' => 'botines_otono.webp',
                    'img1' => 'botines_otono_2.webp',
                    'categoria_id' => 49,
                ],[
                    'nombre' => 'Ropa de Invierno',
                    'descripcion' => 'Descripción de ropa de invierno para Invierno',
                    'precio' => 129.99,
                    'principalImg' => 'abrigo_invierno.jpg',
                    'img1' => 'abrigo_invierno_2.jpg',
                    'categoria_id' => 50,
                ],
                [
                    'nombre' => 'Ropa de Invierno 2',
                    'descripcion' => 'Descripción de ropa de invierno para Invierno',
                    'precio' => 99.99,
                    'principalImg' => 'parka_invierno.jpg',
                    'img1' => 'parka_invierno_2.jpg',
                    'categoria_id' => 50,
                ],
                [
                    'nombre' => 'Ropa de Invierno 3',
                    'descripcion' => 'Descripción de ropa de invierno para Invierno',
                    'precio' => 149.99,
                    'principalImg' => 'chaqueta_plumas_invierno.jpg',
                    'img1' => 'chaqueta_plumas_invierno_2.jpg',
                    'categoria_id' => 50,
                ],
                [
                    'nombre' => 'Ropa de Invierno 4',
                    'descripcion' => 'Descripción de ropa de invierno para Invierno',
                    'precio' => 179.99,
                    'principalImg' => 'abrigo_cuero_invierno.jpg',
                    'img1' => 'abrigo_cuero_invierno_2.jpg',
                    'categoria_id' => 50,
                ],[
                    'nombre' => 'Botas de Invierno',
                    'descripcion' => 'Descripción de las botas para Invierno',
                    'precio' => 89.99,
                    'principalImg' => 'botas_invierno.jpg',
                    'img1' => 'botas_invierno_2.jpg',
                    'categoria_id' => 51, // Asegúrate de que el ID de la categoría "Calzado" sea correcto
                ],
                [
                    'nombre' => 'Botines de Invierno',
                    'descripcion' => 'Descripción de los botines para Invierno',
                    'precio' => 79.99,
                    'principalImg' => 'botines_invierno.jpg',
                    'img1' => 'botines_invierno_2.jpg',
                    'categoria_id' => 51,
                ],
                [
                    'nombre' => 'Zapatos de Invierno',
                    'descripcion' => 'Descripción de los zapatos para Invierno',
                    'precio' => 69.99,
                    'principalImg' => 'zapatos_invierno.jpg',
                    'img1' => 'zapatos_invierno_2.jpg',
                    'categoria_id' => 51,
                ],
                [
                    'nombre' => 'Zapatillas de Invierno',
                    'descripcion' => 'Descripción de las zapatillas para Invierno',
                    'precio' => 59.99,
                    'principalImg' => 'zapatillas_invierno.jpg',
                    'img1' => 'zapatillas_invierno_2.jpg',
                    'categoria_id' => 51,
                ],[
                    'nombre' => 'Accesorios Invierno 1',
                    'descripcion' => 'Descripción de accesorio invierno para Invierno',
                    'precio' => 29.99,
                    'principalImg' => 'bufanda_invierno.jpg',
                    'img1' => 'bufanda_invierno_2.jpg',
                    'categoria_id' => 52, // Asegúrate de que el ID de la categoría "Accesorios" sea correcto
                ],
                [
                    'nombre' => 'Accesorios Invierno 2',
                    'descripcion' => 'Descripción de accesorio invierno para Invierno',
                    'precio' => 19.99,
                    'principalImg' => 'guantes_invierno.jpg',
                    'img1' => 'guantes_invierno_2.jpg',
                    'categoria_id' => 52,
                ],
                [
                    'nombre' => 'Accesorios Invierno 3',
                    'descripcion' => 'Descripción de accesorio invierno para Invierno',
                    'precio' => 24.99,
                    'principalImg' => 'gorro_invierno.jpg',
                    'img1' => 'gorro_invierno_2.jpg',
                    'categoria_id' => 52,
                ],
                [
                    'nombre' => 'Accesorios Invierno 4',
                    'descripcion' => 'DDescripción de accesorio invierno para Invierno',
                    'precio' => 14.99,
                    'principalImg' => 'calcetines_invierno.jpg',
                    'img1' => 'calcetines_invierno_2.jpg',
                    'categoria_id' => 52,
                ],
        ];

        foreach ($productosRopa as $productoData) {
            $producto = Producto::create($productoData);

            $tallas = Talla::all();
            foreach ($tallas as $talla) {
                $producto->tallas()->attach($talla->id);
            }
        }
    }
}
